name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Prepare
        run: yarn && yarn build
      - name: Publish to VSCE
        run: npx vsce publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      - name: Publish to Open VSX
        run: npx ovsx publish -p $OVSX_TOKEN
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
